#!/bin/sh -efu
# Obtain rpm filenames from mirror.yandex.ru.
# This includes CentOS, Fedora, OpenSUSE and a few other distros.

set -o pipefail

mkdir -p m

M=mirror.yandex.ru
mm=$(rsync -n $M:: |cut -f1)

rsync1()
{
	rsync -n -az --compress-level=9 --{con,}timeout=10 "$@" |
	perl -lne 's#.*/##; s#.* ##; print if /\.rpm$/' |sort -u
}

rc=

for m in $mm; do
	[ -s m/$m ] && continue
	if ! rsync1 $M::$m >m/.out; then
		if rsync1 $M::$m >m/.put; then
			# second try succeeds
			mv m/.put m/.out
		elif [ -s m/.out ] && cmp -s m/.out m/.put; then
			# second try fails in exactly the same way,
			# with non-empty output, perhaps due to...
			: permission denied on a bad dir
		else
			echo >&2 failed: $m
			rc=1
			continue
		fi
	fi
	echo >&2 ok: $m
	[ -s m/.out ] && mv m/.out m/$m
done

set +f
wc -l m/*
sort -mu m/* |zstd -6 >rpm.filenames.zst
exit $rc
